AWSTemplateFormatVersion: 2010-09-09
Description: Tableau Server running on Linux (Ubuntu) for The Information Lab Data School Back-to-School 3 Dev Session

Metadata:

  AWS::CloudFormation::Interface:

    ParameterGroups:
      - Label:
          default: AWS Environment and Machine Configuration
        Parameters:
          - InfraStackName
          - InstanceType
          - KeyPairName
          - SourceCIDR
      - Label:
          default: Secrets
        Parameters:
          - TSMUsername
          - TSMPassword
          - TableauServerAdminUsername
          - TableauServerAdminPassword
      - Label:
          default: Registration
        Parameters:
          - AcceptEULA
          - TableauServerLicenseKey
          - RegFirstName
          - RegLastName
          - RegEmail
          - RegCompany
          - RegTitle
          - RegDepartment
          - RegIndustry
          - RegPhone
          - RegCity
          - RegState
          - RegZip
          - RegCountry

    ParameterLabels:
      InfraStackName:
        default: The name you gave the stack that creates the infrastructure for the session
      AcceptEULA:
        default: Accept Tableau End User License Agreement
      InstanceType:
        default: Tableau Amazon EC2 instance type
      KeyPairName:
        default: Key Pair Name
      RegCity:
        default: City
      RegCompany:
        default: Company
      RegCountry:
        default: Country
      RegDepartment:
        default: Department
      RegEmail:
        default: Email Address
      RegFirstName:
        default: First Name
      RegIndustry:
        default: Industry
      RegLastName:
        default: Last Name
      RegPhone:
        default: Phone
      RegState:
        default: State
      RegTitle:
        default: Title
      RegZip:
        default: Zip/Postal Code
      SourceCIDR:
        default: Source CIDR for Access
      TableauServerLicenseKey:
        default: Tableau Activation Key
      TSMUsername:
        default: Tableau Services Manager (TSM) administrator username
      TSMPassword:
        default: Tableau Services Manager (TSM) administrator password
      TableauServerAdminUsername:
        default: Tableau Server administrator username
      TableauServerAdminPassword:
        default: Tableau Server administrator password

Parameters:

  InfraStackName:
    Description: The name of the stack that created the infrastructure
    Type: String
    Default: b2s-dev-infra

  InstanceType:
    AllowedValues:
      - m5.4xlarge
    ConstraintDescription: Must be a valid EC2 instance type.
    Default: m5.4xlarge
    Description: Amazon EC2 instance type
    Type: String

  KeyPairName:
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName

  TableauDownloadLink:
    Default: https://downloads.tableau.com/esdalt/2021.2.1/tableau-server-2021-2-1_amd64.deb
    Description: The download URL for the .deb file of your chosen version from the Tableau Downloads web page
    Type: String

  AcceptEULA:
    AllowedPattern: 'Yes'
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
    Description: 'View the EULA at the Link: https://www.tableau.com/eula'
    Type: String

  RegCity:
    Default: London
    Description: City
    Type: String

  RegCompany:
    Default: TheInformationLab
    Description: Company
    Type: String

  RegCountry:
    Default: UK
    Description: Country
    Type: String

  RegDepartment:
    Default: Consulting
    Description: Department
    Type: String

  RegEmail:
    Default: noreply@theinformationlab.co.uk
    Description: Email
    MinLength: 1
    Type: String

  RegFirstName:
    Default: John
    Description: First Name
    MinLength: 1
    Type: String

  RegIndustry:
    Default: BusinessServices
    Description: Industry
    Type: String

  RegLastName:
    Default: Dunn
    Description: Last Name
    MinLength: 1
    Type: String

  RegPhone:
    Default: '080050001234'
    Description: Phone
    Type: String

  RegState:
    Default: London
    Description: State
    Type: String

  RegTitle:
    Default: Consultant
    Description: Title
    Type: String

  RegZip:
    Default: EC4M5BR
    Description: ZIP/Postal Code
    Type: String

  SourceCIDR:
    Default: 0.0.0.0/0
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: The CIDR address from which you will connect to the instance
    Type: String

  TableauServerLicenseKey:
    Default: ''
    Description: License Key (leave blank for trial)
    Type: String

  TableauServerInstanceProfile:
    Default: Role-for-EC2-full-s3-and-SSM
    Description: Tableau server IAM Instance Profile
    Type: String

  TSMUsername:
    Default: tsm_admin
    AllowedPattern: ^(?!(tableau|tsmagent|admin|root)$)[A-Za-z0-9_]+$
    Description: Tableau Services Manager (TSM) administrator username (cannot be 'tableau' or 'tsmagent' or 'admin' or 'root')
    MaxLength: 30
    Type: String

  TSMPassword:
    Description: Tableau Services Manager (TSM) administrator password
    Default: Tableau123
    MinLength: 6
    Type: String

  TableauServerAdminUsername:
    Default: tableau_admin
    Description: The name of the initial administrator for Tableau Server
    MinLength: 1
    Type: String

  TableauServerAdminPassword:
    Default: Tableau123
    Description: The password of the initial administrator for Tableau Server
    MinLength: 6
    Type: String

Mappings:

  AWSAMIRegionMap:
    eu-west-2:
      AMIID: ami-07dd7edad599ff758

  DefaultConfiguration:
    InstallationConfig:
      AutomatedInstaller: https://s3-us-west-2.amazonaws.com/tableau-quickstart/automated-installer
      PostgresqlDriver: https://downloads.tableau.com/drivers/linux/postgresql/postgresql-42.2.14.jar

    MachineConfiguration:
      SystemVolumeSize: 150
      UbuntuVersion: AMIID

Conditions:

  IsTrial: !Equals
    - ""
    - !Ref TableauServerLicenseKey

Resources:

  TableauServer:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            apt:
              awscli: []
          files:
            /tmp/secrets.properties:
              mode: 640
              content: !Sub |
                tsm_admin_user='${TSMUsername}'
                tsm_admin_pass='${TSMPassword}'
                tableau_server_admin_user='${TableauServerAdminUsername}'
                tableau_server_admin_pass='${TableauServerAdminPassword}'
            /tmp/config.json:
              content:
                {
                  "configEntities":
                    {
                      "gatewaySettings":
                        {
                          "_type": "gatewaySettingsType",
                          "port": 80,
                          "firewallOpeningEnabled": true,
                          "sslRedirectEnabled": true,
                          "publicHost": "localhost",
                          "publicPort": 80,
                        },
                      "identityStore":
                        { "_type": "identityStoreType", "type": "local" },
                    },
                }
            /tmp/tableau-server.deb:
              source: !Ref TableauDownloadLink
            /tmp/automated-installer:
              mode: 550
              source: !FindInMap
                - DefaultConfiguration
                - InstallationConfig
                - AutomatedInstaller
            /tmp/postgresql.jar:
              source: !FindInMap
                - DefaultConfiguration
                - InstallationConfig
                - PostgresqlDriver
            /tmp/registration.json:
              content:
                first_name: !Ref RegFirstName
                last_name: !Ref RegLastName
                email: !Ref RegEmail
                company: !Ref RegCompany
                title: !Ref RegTitle
                department: !Ref RegDepartment
                industry: !Ref RegIndustry
                phone: !Ref RegPhone
                city: !Ref RegCity
                state: !Ref RegState
                zip: !Ref RegZip
                country: !Ref RegCountry
                eula: !Ref AcceptEULA
    Properties:
      SecurityGroupIds:
        - !Ref ServerSecurityGroup
      SubnetId:
        Fn::ImportValue: !Sub ${InfraStackName}-public-subnet-1
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref TableauServerInstanceProfile
      ImageId: !FindInMap
        - AWSAMIRegionMap
        - !Ref AWS::Region
        - !FindInMap
          - DefaultConfiguration
          - MachineConfiguration
          - UbuntuVersion
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp2
            VolumeSize: !FindInMap
              - DefaultConfiguration
              - MachineConfiguration
              - SystemVolumeSize
      EbsOptimized: true
      KeyName: !Ref KeyPairName
      UserData: !Base64
        Fn::Sub:
          - |
            #!/bin/bash -x
            apt-get update
            apt-get upgrade -y
            apt-get install -y python-setuptools

            # Call Init
            /usr/bin/python2.7 /usr/lib/python2.7/dist-packages/easy_install.py --script-dir /opt/aws/bin https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
            /opt/aws/bin/cfn-init --stack ${AWS::StackName} --resource TableauServer --region ${AWS::Region}
            
            # Various machine configs
            hostnamectl set-hostname $(hostnamectl --static)
            setup_sftp() {
                source '/tmp/secrets.properties'
                useradd -s /bin/bash -m "$tsm_admin_user"
                echo -e "$tsm_admin_pass\n$tsm_admin_pass" | passwd "$tsm_admin_user"

            }
            setup_sftp
            unset -f setup_sftp
            export LANG=en_US.UTF-8
            sysctl fs.protected_regular=0
            
            # Copy Postgresql Driver JAR to directory
            mkdir -p /opt/tableau/tableau_driver/jdbc
            cp /tmp/postgresql.jar /opt/tableau/tableau_driver/jdbc
            
            # Install Tableau Server
            install() {
                source '/tmp/secrets.properties'
                /tmp/automated-installer -a $tsm_admin_user -f /tmp/config.json -r /tmp/registration.json -s /tmp/secrets.properties ${LicenseString} -v --accepteula --force /tmp/tableau-server.deb
            }
            install
            unset -f install
            
            # Signal successful completion
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource TableauServer --region ${AWS::Region}
            
            # Cleanup
            rm -f /tmp/config.json
            rm -f /tmp/registration.json
            rm -f /tmp/secrets.properties
            rm -f /tmp/tableau-server.deb
            rm -f /tmp/automated-installer
          - LicenseString:
              Fn::If:
                - IsTrial
                - ""
                - !Sub -k ${TableauServerLicenseKey}
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-cfn-tableau-server-linux
    CreationPolicy:
      ResourceSignal:
        Timeout: PT60M

  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref TableauServer
      Domain: vpc

  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Fn::ImportValue: !Sub ${InfraStackName}-vpc
      GroupDescription:
        Enable HTTP access via port 80 and HTTPS access on port 8850,
        and SSH access from the provided network CIDR
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref SourceCIDR
        - IpProtocol: tcp
          FromPort: 8850
          ToPort: 8850
          CidrIp: !Ref SourceCIDR
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SourceCIDR

Outputs:

  InstanceID:
    Description: EC2 InstanceID of the instance running Tableau Server
    Value: !Ref TableauServer
    Export:
      Name: !Sub ${AWS::StackName}-InstanceId

  PublicIPAddress:
    Description: Public IP Address of instance running Tableau Server
    Value: !GetAtt TableauServer.PublicIp

  TableauServicesManagerURL:
    Description: URL for the TSM Web UI
    Value: !Join
      - ""
      - - https://
        - !GetAtt TableauServer.PublicIp
        - :8850/

  TableauServerURL:
    Description: URL for the Tableau Server
    Value: !Join
      - ""
      - - http://
        - !GetAtt TableauServer.PublicDnsName
        - /

  SSH:
    Description: SSH to the Tableau Server instance using the keypair you provided
    Value: !Join
      - ""
      - - ubuntu@
        - !GetAtt TableauServer.PublicDnsName
